name: 'Publish ghPages coverage report'
description: 'Publishes test coverage report to GitHub Pages'
inputs:
  coverageDirectory:
    description: 'The directory of the coverage report'
    required: true
    default: './coverage/lcov-report'
  ghPagesBranch:
    description: 'The branch to which to publish the GitHub Pages'
    required: true
    default: 'gh-pages'
runs:
  using: 'node20'
  main: 'dist/index.js'